# Generated by Django 4.1.5 on 2023-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='expense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='savings',
            field=models.FloatField(default=0, null=True),
        ),
    ]
