# Generated by Django 4.2 on 2023-05-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_balance_user_profile_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='income',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='savings',
        ),
    ]
